grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      - 8
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 40
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      - 8
      n_estimators:
      - 50
      - 100